=== Zied-Belkhiria-Mhp/product-test-data-generator/tdg/src/main/resources/schema/BPDM_v1.1.0.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",

    "type": "object",
    "additionalProperties": false,
    "properties": {
        "bpn": {
            "type": "string"
        },
        "identifiers": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Identifier"
            }
        },
        "names": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/LegalForm"
            }
        },
        "legalForm": {
            "$ref": "#/definitions/LegalForm"
        },
        "status": {
            "type": "string"
        },
        "addresses": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Address"
            }
        },
        "profile": {
            "$ref": "#/definitions/Profile"
        },
        "relations": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Relation"
            }
        },
        "types": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "bankAccounts": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/BankAccount"
            }
        },
        "roles": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "addresses",
        "bankAccounts",
        "bpn",
        "identifiers",
        "legalForm",
        "names",
        "profile",
        "relations",
        "roles",
        "status",
        "types"
    ],
       
    "definitions": {
        "Address": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "identifiers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Identifier"
                    }
                },
                "careOf": {
                    "$ref": "#/definitions/LegalForm"
                },
                "countryCode": {
                    "type": "string"
                },
                "administrativeAreas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AdministrativeArea"
                    }
                },
                "postCodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LegalForm"
                    }
                },
                "localities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LegalForm"
                    }
                },
                "thoroughfares": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LegalForm"
                    }
                },
                "premises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LegalForm"
                    }
                },
                "postalDeliveryPoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LegalForm"
                    }
                },
                "type": {
                    "type": "string"
                },
                "versions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Version"
                    }
                }
            },
            "required": [
                "administrativeAreas",
                "careOf",
                "countryCode",
                "identifiers",
                "localities",
                "postCodes",
                "postalDeliveryPoints",
                "premises",
                "thoroughfares",
                "type",
                "versions"
            ],
            "title": "Address"
        },
        "AdministrativeArea": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "codes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Code"
                    }
                },
                "type": {
                    "type": "string"
                }
            },
            "required": [
                "codes",
                "name",
                "type"
            ],
            "title": "AdministrativeArea"
        },
        "Code": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "value": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            },
            "required": [
                "type",
                "value"
            ],
            "title": "Code"
        },
        "Identifier": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "value": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "registration": {
                    "$ref": "#/definitions/Registration"
                }
            },
            "required": [
                "number",
                "shortName",
                "type",
                "value"
            ],
            "title": "Identifier"
        },
        "Registration": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "hardeningGrade": {
                    "type": "string"
                },
                "issuingAgency": {
                    "$ref": "#/definitions/LegalForm"
                },
                "status": {
                    "type": "string"
                },
                "initialRegistration": {
                    "type": "string",
                    "format": "date-time"
                },
                "lastUpdate": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "hardeningGrade",
                "initialRegistration",
                "issuingAgency",
                "lastUpdate",
                "status"
            ],
            "title": "Registration"
        },
        "LegalForm": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "value": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            },
            "required": [
                "number",
                "shortName",
                "value"
            ],
            "title": "LegalForm"
        },
        "Version": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "characterSet": {
                    "type": "string"
                },
                "languageCode": {
                    "type": "string"
                }
            },
            "required": [
                "characterSet",
                "languageCode"
            ],
            "title": "Version"
        },
        "BankAccount": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "trustScores": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "currencyCode": {
                    "type": "string"
                },
                "internationalBankAccountIdentifier": {
                    "type": "string"
                },
                "internationalBankIdentifier": {
                    "type": "string"
                },
                "nationalBankAccountIdentifier": {
                    "type": "string"
                },
                "nationalBankIdentifier": {
                    "type": "string"
                }
            },
            "required": [
                "currencyCode",
                "internationalBankAccountIdentifier",
                "internationalBankIdentifier",
                "nationalBankAccountIdentifier",
                "nationalBankIdentifier",
                "trustScores"
            ],
            "title": "BankAccount"
        },
        "Profile": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "classifications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Identifier"
                    }
                }
            },
            "required": [
                "classifications"
            ],
            "title": "Profile"
        },
        "Relation": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "relationClass": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "startNode": {
                    "type": "string"
                },
                "endNode": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "endedAt": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "endNode",
                "endedAt",
                "relationClass",
                "startNode",
                "startedAt",
                "type"
            ],
            "title": "Relation"
        }
    }
}

=== Zied-Belkhiria-Mhp/product-test-data-generator/tdg/src/main/resources/datatemplate/BusinessPartner_v0.1.1.json
{
  "bpn": "BPNL1234567890ZZ",
  "identifiers": [
    {
      "value": "999999",
      "shortName": "HR",
      "number": 0,
      "type": "Handelsregister",
      "registration": {
        "hardeningGrade": "GOLD",
        "issuingAgency": {
          "value": "",
          "shortName": "",
          "number": 0
        },
        "status": "ISSUED",
        "initialRegistration": "2019-01-27T07:33:55.865Z",
        "lastUpdate": "2022-01-27T07:33:55.865Z"
      }
    }
  ],
  "names": [
    {
      "value": "Test Company",
      "shortName": "Test",
      "number": 0,
      "type": "ACRONYM"
    }
  ],
  "legalForm": {
    "value": "Aktiengesellschaft",
    "shortName": "AG",
    "number": 0,
    "type": ""
  },
  "status": "ACTIVE",
  "addresses": [
    {
      "identifiers": [
        {
          "value": "9999",
          "shortName": "HR",
          "number": 0,
          "type": "Handelsregister",
          "registration": {
            "hardeningGrade": "GOLD",
            "issuingAgency": {
              "value": "None",
              "shortName": "n/a",
              "number": 0
            },
            "status": "ISSUED",
            "initialRegistration": "2019-01-27T07:33:55.865Z",
            "lastUpdate": "2022-01-27T07:33:55.865Z"
          }
        }
      ],
      "careOf": {
        "value": "",
        "shortName": "",
        "number": 0
      },
      "countryCode": "DE",
      "administrativeAreas": [
        {
          "name": "",
          "codes": [
            {
              "value": "",
              "type": ""
            }
          ],
          "type": "COUNTY"
        }
      ],
      "postCodes": [
        {
          "value": "80809",
          "shortName": "",
          "number": 0,
          "type": "CEDEX"
        }
      ],
      "localities": [
        {
          "value": "Munich",
          "shortName": "",
          "number": 0,
          "type": "BLOCK"
        }
      ],
      "thoroughfares": [
        {
          "value": "",
          "shortName": "",
          "number": 0,
          "type": "INDUSTRIAL_ZONE"
        }
      ],
      "premises": [
        {
          "value": "",
          "shortName": "",
          "number": 0,
          "type": "BUILDING"
        }
      ],
      "postalDeliveryPoints": [
        {
          "value": "",
          "shortName": "",
          "number": 0,
          "type": "INTERURBAN_DELIVERY_POINT"
        }
      ],
      "type": "BRANCH_OFFICE",
      "versions": [
        {
          "characterSet": "ARABIC",
          "languageCode": "undefined"
        }
      ]
    }
  ],
  "profile": {
    "classifications": [
      {
        "value": "",
        "shortName": "",
        "number": 0,
        "type": "NACE"
      }
    ]
  },
  "relations": [
    {
      "relationClass": "CDQ_HIERARCHY",
      "type": "CX_LEGAL_SUCCESSOR_OF",
      "startNode": "",
      "endNode": "",
      "startedAt": "2022-01-27T07:33:55.865Z",
      "endedAt": "2022-01-27T07:33:55.865Z"
    }
  ],
  "types": [
    "BRAND"
  ],
  "bankAccounts": [
    {
      "trustScores": [
        0
      ],
      "currencyCode": "UNDEFINED",
      "internationalBankAccountIdentifier": "000000000",
      "internationalBankIdentifier": "000000000",
      "nationalBankAccountIdentifier": "000000000",
      "nationalBankIdentifier": "000000000"
    }
  ],
  "roles": [
    ""
  ]
}
